function howMany() {
    return 60
}

function itemData() {
    items = [
        {"id":0, "name":"Crown Town Pants", "price":852.99, "tags":['Pants', 'sienna', 'cornflowerblue', 'Urban', 'Aquatic', 'Hiking', 'Aquatic']},
        {"id":1, "name":"PowSlayer Twisted Shoes", "price":508.99, "tags":['Shoes', 'tan', 'deeppink', 'Aquatic']},
        {"id":2, "name":"Storm Town Coat", "price":439.99, "tags":['Coat', 'orchid', 'forestgreen', 'Hiking']},
        {"id":3, "name":"Crown Storm Hat", "price":366.99, "tags":['Hat', 'darkslategray', 'rosybrown', 'Climbing']},
        {"id":4, "name":"Micro Puff Shift Jacket", "price":333.99, "tags":['Jacket', 'slategray', 'midnightblue', 'Urban']},
        {"id":5, "name":"Trident Groove Pants", "price":955.99, "tags":['Pants', 'silver', 'limegreen', 'Winter', 'Climbing', 'Climbing', 'Urban']},
        {"id":6, "name":"Sunset Town Shirt", "price":158.99, "tags":['Shirt', 'deeppink', 'paleturquoise', 'Adventure', 'Hiking', 'NIghtwear', 'Climbing']},
        {"id":7, "name":"PowSlayer Storm Pants", "price":62.99, "tags":['Pants', 'olivedrab', 'darkorchid', 'Adventure', 'Adventure']},
        {"id":8, "name":"Sunset Storm Hat", "price":385.99, "tags":['Hat', 'turquoise', 'linen', 'Urban', 'Aquatic']},
        {"id":9, "name":"Storm Twisted Pants", "price":269.99, "tags":['Pants', 'coral', 'saddlebrown', 'Winter', 'Urban']},
        {"id":10, "name":"PowSlayer Storm Pants", "price":741.99, "tags":['Pants', 'dimgray', 'midnightblue', 'Adventure', 'Hiking', 'Adventure', 'Aquatic']},
        {"id":11, "name":"Crown Town Shoes", "price":856.99, "tags":['Shoes', 'slategray', 'mediumseagreen', 'Winter', 'NIghtwear', 'Adventure']},
        {"id":12, "name":" Shift Shoes", "price":541.99, "tags":['Shoes', 'royalblue', 'yellowgreen', 'Urban']},
        {"id":13, "name":"Sunset  Gloves", "price":372.99, "tags":['Gloves', 'darkturquoise', 'Urban', 'Urban', 'Climbing', 'Adventure']},
        {"id":14, "name":"Sunset Trick Coat", "price":756.99, "tags":['Coat', 'purple', 'crimson', 'Hiking', 'Urban', 'NIghtwear', 'Adventure']},
        {"id":15, "name":"Sunset Twisted Shirt", "price":427.99, "tags":['Shirt', 'seagreen', 'Urban', 'Aquatic', 'Urban', 'Climbing']},
        {"id":16, "name":"Sunset Storm Pants", "price":289.99, "tags":['Pants', 'indianred', 'slateblue', 'Climbing']},
        {"id":17, "name":"Crown  Gloves", "price":439.99, "tags":['Gloves', 'firebrick', 'mediumvioletred', 'Aquatic']},
        {"id":18, "name":"Sunset Shift Shirt", "price":174.99, "tags":['Shirt', 'gold', 'sienna', 'Urban']},
        {"id":19, "name":"Sunset Storm Gloves", "price":994.99, "tags":['Gloves', 'gray', 'turquoise', 'Hiking', 'NIghtwear']},
        {"id":20, "name":"Storm Groove Jacket", "price":551.99, "tags":['Jacket', 'darkmagenta', 'seagreen', 'Aquatic', 'Hiking']},
        {"id":21, "name":"PowSlayer Storm Jacket", "price":826.99, "tags":['Jacket', 'khaki', 'Climbing', 'NIghtwear']},
        {"id":22, "name":"Micro Puff Twisted Glasses", "price":188.99, "tags":['Glasses', 'dodgerblue', 'limegreen', 'Climbing', 'Climbing']},
        {"id":23, "name":"Sunset  Glasses", "price":367.99, "tags":['Glasses', 'chocolate', 'Urban', 'NIghtwear', 'Aquatic']},
        {"id":24, "name":"Powder Tailed Gloves", "price":65.99, "tags":['Gloves', 'lightgreen', 'limegreen', 'Urban', 'Climbing', 'Hiking', 'NIghtwear']},
        {"id":25, "name":"Trident Groove Glasses", "price":23.99, "tags":['Glasses', 'darkorchid', 'steelblue', 'Winter', 'Urban', 'NIghtwear', 'Adventure']},
        {"id":26, "name":"Trident Trick Hat", "price":843.99, "tags":['Hat', 'crimson', 'darkslategray', 'Climbing', 'Winter']},
        {"id":27, "name":" Town Coat", "price":54.99, "tags":['Coat', 'gray', 'steelblue', 'NIghtwear', 'Hiking']},
        {"id":28, "name":"Powder  Jacket", "price":266.99, "tags":['Jacket', 'plum', 'darkolivegreen', 'Winter', 'Winter', 'Climbing', 'Winter']},
        {"id":29, "name":"Crown Groove Glasses", "price":863.99, "tags":['Glasses', 'palegoldenrod', 'cornflowerblue', 'Hiking', 'Hiking', 'NIghtwear']},
        {"id":30, "name":"Storm Town Pants", "price":67.99, "tags":['Pants', 'royalblue', 'mediumpurple', 'Hiking', 'Climbing', 'Adventure']},
        {"id":31, "name":" Twisted Hat", "price":669.99, "tags":['Hat', 'midnightblue', 'Winter', 'Winter', 'Adventure']},
        {"id":32, "name":" Twisted Jacket", "price":876.99, "tags":['Jacket', 'darkkhaki', 'mediumpurple', 'Adventure', 'Aquatic', 'Urban']},
        {"id":33, "name":" Storm Shoes", "price":536.99, "tags":['Shoes', 'yellowgreen', 'darkgray', 'Aquatic']},
        {"id":34, "name":"Trident  Shoes", "price":534.99, "tags":['Shoes', 'slateblue', 'darkturquoise', 'NIghtwear', 'Climbing', 'Climbing']},
        {"id":35, "name":"Powder Twisted Shirt", "price":153.99, "tags":['Shirt', 'red', 'wheat', 'Hiking', 'Adventure']},
        {"id":36, "name":"Crown Tailed Shoes", "price":400.99, "tags":['Shoes', 'sienna', 'lightgreen', 'Aquatic']},
        {"id":37, "name":"Micro Puff Shift Gloves", "price":181.99, "tags":['Gloves', 'royalblue', 'pink', 'Climbing', 'Hiking', 'Hiking']},
        {"id":38, "name":"Sunset Insulated Pants", "price":277.99, "tags":['Pants', 'forestgreen', 'darkgray', 'Urban', 'Urban', 'Winter', 'Winter']},
        {"id":39, "name":"Powder Storm Glasses", "price":768.99, "tags":['Glasses', 'crimson', 'deepskyblue', 'Hiking', 'Climbing', 'Climbing']},
        {"id":40, "name":"Crown Town Hat", "price":149.99, "tags":['Hat', 'paleturquoise', 'dodgerblue', 'Climbing', 'Winter']},
        {"id":41, "name":"Micro Puff Groove Glasses", "price":778.99, "tags":['Glasses', 'turquoise', 'springgreen', 'Hiking', 'Winter', 'Hiking']},
        {"id":42, "name":"Trident Town Pants", "price":728.99, "tags":['Pants', 'blue', 'Adventure', 'NIghtwear', 'NIghtwear']},
        {"id":43, "name":"Sunset Twisted Coat", "price":88.99, "tags":['Coat', 'orchid', 'darkslateblue', 'Aquatic']},
        {"id":44, "name":"Storm Town Coat", "price":546.99, "tags":['Coat', 'paleturquoise', 'tomato', 'Climbing', 'Adventure']},
        {"id":45, "name":"Crown Shift Shirt", "price":865.99, "tags":['Shirt', 'maroon', 'Aquatic', 'NIghtwear', 'Climbing']},
        {"id":46, "name":"Micro Puff Trick Jacket", "price":519.99, "tags":['Jacket', 'royalblue', 'darkmagenta', 'Aquatic', 'Winter', 'Hiking', 'Climbing']},
        {"id":47, "name":"Micro Puff Shift Jacket", "price":892.99, "tags":['Jacket', 'indigo', 'mediumaquamarine', 'Climbing', 'Winter', 'Climbing']},
        {"id":48, "name":"  Coat", "price":905.99, "tags":['Coat', 'mediumpurple', 'Winter', 'Adventure']},
        {"id":49, "name":"Sunset Tailed Shirt", "price":941.99, "tags":['Shirt', 'limegreen', 'Adventure', 'Climbing']},
        {"id":50, "name":"Trident Town Gloves", "price":152.99, "tags":['Gloves', 'mediumseagreen', 'magenta', 'NIghtwear']},
        {"id":51, "name":"Crown Twisted Gloves", "price":223.99, "tags":['Gloves', 'lightgreen', 'crimson', 'Adventure']},
        {"id":52, "name":"Powder Shift Jacket", "price":394.99, "tags":['Jacket', 'palegoldenrod', 'NIghtwear', 'Aquatic', 'Urban', 'Aquatic']},
        {"id":53, "name":"Sunset Trick Coat", "price":625.99, "tags":['Coat', 'mediumvioletred', 'powderblue', 'Climbing', 'Winter']},
        {"id":54, "name":"PowSlayer  Pants", "price":467.99, "tags":['Pants', 'mediumturquoise', 'lightseagreen', 'NIghtwear']},
        {"id":55, "name":" Tailed Shirt", "price":696.99, "tags":['Shirt', 'black', 'orange', 'Hiking']},
        {"id":56, "name":"Powder Shift Glasses", "price":386.99, "tags":['Glasses', 'limegreen', 'teal', 'Hiking', 'Urban', 'Winter']},
        {"id":57, "name":"Crown Trick Jacket", "price":968.99, "tags":['Jacket', 'hotpink', 'Adventure', 'NIghtwear', 'Climbing']},
        {"id":58, "name":" Tailed Glasses", "price":426.99, "tags":['Glasses', 'royalblue', 'palevioletred', 'Climbing', 'Climbing', 'Urban']},
        {"id":59, "name":"Sunset Groove Shirt", "price":747.99, "tags":['Shirt', 'lightblue', 'mediumblue', 'Winter', 'Hiking', 'Aquatic', 'NIghtwear']},
                
    ]
    return items
}